# Generated by Django 5.2.5 on 2026-04-29 03:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_inventoryitem_location_materialrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('delivery_id', models.AutoField(primary_key=True, serialize=False)),
                ('supplier', models.CharField(max_length=255)),
                ('location', models.CharField(choices=[('warehouse', 'Warehouse'), ('yard', 'Yard'), ('jobsite', 'Jobsite')], default='warehouse', max_length=20)),
                ('notes', models.TextField(blank=True, default='')),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('received_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries_received', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DeliveryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=255)),
                ('item_type', models.CharField(choices=[('material', 'Material'), ('equipment', 'Equipment')], default='material', max_length=20)),
                ('quantity', models.PositiveIntegerField()),
                ('description', models.TextField(blank=True, default='')),
                ('delivery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='api.delivery')),
                ('inventory_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='delivery_items', to='api.inventoryitem')),
            ],
        ),
    ]
