# Generated by Django 5.2.5 on 2026-05-05 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_jobsite'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobsite',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='jobsite_photos/'),
        ),
    ]
