# Generated by Django 5.2.5 on 2026-05-05 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_jobsite_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='packing_slip_photo',
            field=models.ImageField(blank=True, null=True, upload_to='packing_slips/'),
        ),
    ]
