# Generated by Django 5.2.5 on 2026-05-05 02:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_delivery_packing_slip_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobsite',
            name='photo',
        ),
    ]
