# Generated by Django 5.2.5 on 2026-05-05 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_inventoryitem_reported_missing_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='inventory_photos/'),
        ),
    ]
