# Generated by Django 5.2.5 on 2026-05-05 16:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_materialrequest_jobsite'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialrequest',
            name='new_item_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='materialrequest',
            name='new_item_type',
            field=models.CharField(blank=True, choices=[('material', 'Material'), ('equipment', 'Equipment')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='materialrequest',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='api.inventoryitem'),
        ),
        migrations.AlterField(
            model_name='materialrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('denied', 'Denied'), ('fulfilled', 'Fulfilled'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
    ]
